---
version: "3.5"

services:

  vpn:
    image: dperson/openvpn-client
    container_name: vpn
    restart: unless-stopped
    networks:
      - vpn_network
    cap_add:
      - net_admin
    security_opt:
      - label:disable
    devices:
      - /dev/net/tun
    dns:
      - ${PRIMARY_DNS}
      - ${SECONDARY_DNS}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_STORAGE}/openvpn_client:/vpn
    environment:
      - TZ=${TZ_ALT}
    command: ' -f "" -r 192.168.1.0/24 -p 6881'
    # for some reason the following format had more issues being read-in correctly for this container,
    #   though it is a much cleaner way to organize the information and add comments
    # command: [
    #   '-f ""',  # configures firewall to only allow traffic while vpn is connected. the "" is intentional, per the project's README
    #   '-r 192.168.1.0/24',
    #   '-p 6881',  # qbittorrent port forward
    # ]

  letsencrypt:
    image: lscr.io/linuxserver/swag
    container_name: letsencrypt
    restart: unless-stopped
    networks:
      - external_web_network
      - external_game_network
      - bitwarden_network
      - paperless_network
    cap_add:
      - NET_ADMIN
    security_opt:
      - no-new-privileges=true
    # doesn't matter which ports are exposed, as long as it doesn't conflict with others and is forwarded through your router to this docker host and port
    ports:
      # - 5080:80  # use cloudflare redirect to https port instead
      - 5443:443  # the port to forward from outside web 443 traffic to this machine at 5443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_STORAGE}/letsencrypt:/config
    environment:
      - TZ=${TZ}
      - PGID=${PGID}
      - PUID=${PUID}
      - STAGING=false
      - DHLEVEL=4096
      - DOCKER_MODS=linuxserver/mods:swag-maxmind
      # - DOCKER_MODS=ghcr.io/linuxserver/mods:swag-crowdsec
      # - DOCKER_MODS=linuxserver/mods:swag-maxmind|ghcr.io/linuxserver/mods:swag-crowdsec

  nginx_internal:
    image: nginx
    container_name: nginx_internal
    restart: unless-stopped
    ports:
      # - 80:80  # only use https where possible, even if only a self signed cert
      - 443:443
    networks:
      - internal_web_network
      - vpn_network
    security_opt:
      - no-new-privileges=true
    depends_on:
      - vpn
      - radarr
      - sonarr
      - bazarr
      - lidarr
      - readarr
      - prowlarr
      - qbittorrent
      - nzbget
      - duplicati
      - organizr
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_STORAGE}/nginx_internal/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${DOCKER_STORAGE}/nginx_internal/nginx/conf.d:/etc/nginx/conf.d
      - ${DOCKER_STORAGE}/nginx_internal/nginx/ssl:/etc/nginx/ssl
      - ${DOCKER_STORAGE}/nginx_internal/nginx/logs:/etc/nginx/logs

  cloudflare-homedomain:
    image: joshuaavalon/cloudflare-ddns
    container_name: cloudflare-homedomain
    restart: unless-stopped
    environment:
      - TTL=1
      - PROXY=true

  cloudflare-gamedomain:
    image: joshuaavalon/cloudflare-ddns
    container_name: cloudflare-gamedomain
    restart: unless-stopped
    environment:
      - TTL=1
      - PROXY=true

  # duckdns:
  #   image: lscr.io/linuxserver/duckdns
  #   container_name: duckdns
  #   restart: unless-stopped
  #   environment:
  #     - TZ=${TZ}
  #     - PGID=${PGID}
  #     - PUID=${PUID}

networks:
  vpn_network:
  internal_web_network:
  external_web_network:
  external_game_network:
  nextcloud_network:
  paperless_network:
